= Automatic Updating of the Desktop App
:toc: right
:description: The Automatic Updater ensures that you always have the latest features and bug fixes for your Desktop App.

include::partial$conditional_naming.adoc[]

== Introduction

{description} The Automatic Updater only works on Windows computers. macOS Linux users must use the same process they used to install the Desktop App. However, the updater will check for updates and notify you when a new version is available.

IMPORTANT: When planning to upgrade from a Desktop app release <= 2.5 to a release >=5.0 you must make an intermediary step to release 4.0 before doing the final upgrade.

== Basic Workflow

The following sections describe how to use the Automatic Updater on different operating systems.

On the menu:Settings[About] page, you can define the update channel. Depending on the selected channel, different versions of the {ini_name} Desktop App will be available. Note that you cannot switch channels back and forth. Once a change is made, it cannot be undone.

Depending on the operating system (OS), either a download and installation process begins, or a notification window pops up when a new release is available, prompting you to take further action.

=== Windows

If an update is available and has been downloaded successfully, the {ini_name} Desktop App will start a silent update before its next launch and then restart itself. If the silent update fails, the {ini_name} Desktop App offers a manual download.

NOTE: Administrative privileges are required to perform the update.

=== macOS

If a new update is available, the {ini_name} Desktop App initializes a *pop-up dialog* to alert you of the update and requests that you update to the latest version. This is the default process for macOS applications.

=== Linux

If a new update is available, the {ini_name} Desktop App initializes a *pop-up dialog* to alert you of the update and requests that you update to the latest version. Update the {ini_name} Desktop App according to the installation method used.

== Preventing Automatic Updates

In controlled environments such as companies or universities, you may not want to enable the auto-update mechanism because it interferes with deployment tools and policies. To address this issue, you can disable the auto-updater entirely. The following sections describe how to do so for different operating systems.

More information about the configuration file can be found in the xref:advanced_usage/configuration_file.adoc[Configuration File] documentation.

=== Windows Environments

Users can disable automatic updates by adding this line to the `[General]` section of their `owncloud.cfg` files:

`owncloud.cfg` is usually located in: +
`%AppData%\ownCloud\owncloud.cfg`

[source,cfg]
----
skipUpdateCheck=true
----

Windows administrators have two methods for preventing automatic updates in Windows environments. The first method allows users to override the automatic update check mechanism. The second method, on the other hand, prevents any manual overrides.

To prevent automatic updates, but allow manual overrides:

.  Edit these Registry keys:

[source]
----
a. (32-bit-Windows) HKEY_LOCAL_MACHINE\Software\ownCloud\ownCloud
b. (64-bit-Windows) HKEY_LOCAL_MACHINE\Software\Wow6432Node\ownCloud\ownCloud
----

[start=2]
.  Add the key `skipUpdateCheck` (of type DWORD).
.  Specify a value of `1` to the machine.

To override this key manually, use the same value in `HKEY_CURRENT_USER`. To prevent automatic updates and disallow manual overrides, do the following:

NOTE: This is the preferred method for controlling updater behavior through group policies.

.  Edit this Registry key:

[source]
----
HKEY_LOCAL_MACHINE\Software\Policies\ownCloud\ownCloud
----

[start=2]
.  Add the key `skipUpdateCheck` (of type DWORD).
.  Specify a value of `1` to the machine.

NOTE: The key names of enterprise-branded Desktop Apps are set during the branding process using the Application Vendor and Application Name fields.

Your key names look like this:

[source]
----
HKEY_LOCAL_MACHINE\Software\Policies\myCompanyName\myAppName
----

=== macOS Environments

In the macOS operating system, you can disable the automatic update mechanism by copying the file: +
`owncloud.app/Contents/Resources/deny_autoupdate_com.owncloud.desktopclient.plist` to +
`/Library/Preferences/com.owncloud.desktopclient.plist`

=== Linux Environments

Since the Linux Desktop App does not have automatic update functionality, there is no need to remove the automatic update check. However, if you want to disable automatic updates, edit your Desktop App configuration file: `$HOME/.config/ownCloud/owncloud.cfg`. Add this line to the `[General]` section:

[source,cfg]
----
skipUpdateCheck=true
----
