= Introduction to the Desktop App
:toc: right
:toclevels: 2
:description: This is the description of the Desktop App which allows you to synchronize your files from connected servers to your local computer. 

include::partial$conditional_naming.adoc[]

== Introduction

{description} The app is available for *Windows*, *macOS*, and various *Linux* distributions.

== Compatiblility

NOTE: Starting with {ini_name} version 7.0, the Desktop App will no longer support ownCloud Server, only ownCloud Infinite Scale. To use the Desktop App with ownCloud Server, use version 6.x instead.

== Key Benefits

The Desktop App enables you to:

* Specify one or more servers to connect to.
* Specify one or more resources to synchronize.
* Automatically synchronize data in both directions.
* Manage synchronization conflicts, if any.

== Target Audience

This documentation is intended for *users* and personnel responsible for *deployments*.

== Prerequisites

Once the Desktop App is deployed, the configuration and use of the application varies very little across operating systems (OS).

The deployment guide describes the requirements in detail::
--
* For all OS
** The Desktop App requires a minimum version for the OS to run.
* OS dependent
** There may be additional requirements that depend on the OS used.
--

== Important Information

Before you configure synchronization, you should consider the following:

NOTE: Synchronizing the same directory with {ini_name} and other synchronization software such as Unison, rsync, Microsoft Windows Offline Folders, or other cloud services such as Dropbox or Microsoft OneDrive is not supported and should not be attempted. In the worst case, synchronizing folders or files using the Desktop App and other synchronization software or services could result in data loss.
