= Removing the Desktop App
:toc: right
:description: This page describes the steps necessary to remove the Desktop App, if permitted by the company.

include::partial$conditional_naming.adoc[]

== Introduction

{description}

== Removing the Binary

Follow your operating system's instructions for removing the Desktop App binary.

When using an AppImage, just delete the AppImage file.

== Removing the Configuration File

If you remove the Desktop App, the configuration file remains on your system. If you then decide to reinstall the Desktop App, you won't need to enter the connection information again.

If you want to cleanly remove the Desktop App, you must manually delete the configuration file. The location of the configuration file depends on the operating system and can be found in xref:advanced_usage/configuration_file.adoc[Configuration File].

== Windows Navigation Sidebar

If you have removed the Desktop App but still have the {ini_name} shortcut or icon in the Windows navigation bar, follow these steps to remove it:

1. Open `regedit`. (press the Windows Key and type: regedit)
2. Search ( btn:[CTRL or STRG + F] ) for the name of the Desktop App, in this case `{bin_name}.exe`.
3. Press btn:[F3] for next search results.
4. Look for the key `System.IsPinnedToNameSpaceTree`.
5. Right-click on the key name, change, set to `0` instead of `1`.

You need to do this twice. Once for the `x64' and `x32' system settings.

Once this is done, you don't need to restart, just open and close Explorer -- the sidebar is clean.
