# note that this site.yml file is for local building and testing only
site:
  title: ownCloud Desktop App Documentation
  url: https://doc.owncloud.com
  start_page: desktop::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # the docs-xxx are just present for the test build to satisfy used references
  # the real build is made in the docs repo using correct values
  - url: https://github.com/owncloud/docs-client-branding.git
    branches:
    - master

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    idprefix: ''
    idseparator: '-'
    experimental: ''
#   desktop
    latest-desktop-version: '4.0'
    previous-desktop-version: '3.2'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js
