# note that this site.yml file is for local building and testing only
site:
  title: ownCloud Desktop App Documentation
  url: https://doc.owncloud.com
  start_page: desktop::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
#   desktop
    latest-desktop-version: '4.1'
    previous-desktop-version: '4.0'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js
