= Appendix Building the Client
:toc: right
:client-source-url: https://github.com/owncloud/client
:ownbuild-url: https://github.com/owncloud/ownbuild#readme
:description: This section explains how to build the ownCloud Client from source for all major platforms. You should read this section if you want to compile the desktop client on your own.
:page-aliases: building.adoc

== Introduction

{description} Usually building a client locally is helpful when contributing to the source and testing your result. Note that build instructions are subject to change as development proceeds. See the {client-source-url}[ownCloud Desktop Client] source for contributions to the client.

== Building the Desktop Client

ownCloud provides an own repository as starting point for building the client. All necessary details can be found there. See the {ownbuild-url}[ownbuild repository] to proceed.

== Compiling via ownBrander

If you don’t want to go through the challenges of doing all the compiling work manually, you can use
xref:{latest-branding-version}@branded_clients:ROOT:index.adoc[ownBrander] to create installer images for all platforms.
